apiVersion: v2
name: immich
version: 0.0.0
dependencies:
  - name: immich
    repository: https://immich-app.github.io/immich-charts
    version: 0.9.0
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.22.1
